name: Test Pipeline

on:
  push:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API tests
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
        run: pytest api_tests --alluredir=allure-results/api -v

      - name: Upload API Allure results
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-results
          path: allure-results/api

  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run UI tests
        run: pytest tests --alluredir=allure-results/ui -v

      - name: Upload UI Allure results
        uses: actions/upload-artifact@v4
        with:
          name: ui-allure-results
          path: allure-results/ui
